version: "3.8"
services:
  app-dev:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: npm run start
  app-test:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    ports:
      - "4000"
    volumes:
      - .:/app
    command: npm run test
